sudo: required 
services:
  - docker

before_install:
  - docker build -t chudi/docker-react -f Dockerfile.dev .


script:
  - docker run chudi/docker-react npm run test -- --coverage 


deploy:
  provider: elasticbeanstalk
  regoin: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-134567643"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    